# ============================================================================
# Contact Sensor Auto-Monitor Package
# ============================================================================
#
# This package automatically monitors ALL contact sensors in your Home Assistant
# instance and sends notifications when they're left open too long.
#
# Unlike blueprints, this requires NO automation per sensor. Add a new contact
# sensor, assign it to an area/floor, and it automatically works.
#
# Installation: See INSTALLATION.md or README.md for complete instructions
# ============================================================================


# ----------------------------------------------------------------------------
# Input Number: Global Delay
# ----------------------------------------------------------------------------
input_number:
  contact_sensor_delay_minutes:
    name: Contact Sensor Delay (Minutes)
    min: 1
    max: 1440
    step: 1
    initial: 10
    mode: box
    icon: mdi:timer


# ----------------------------------------------------------------------------
# Input Boolean: Global Critical Notification
# ----------------------------------------------------------------------------
input_boolean:
  contact_sensor_critical_alert:
    name: Contact Sensor Critical Alert
    initial: false
    icon: mdi:alert


# ----------------------------------------------------------------------------
# Automation: Contact Sensor Monitor (All Sensors)
# ----------------------------------------------------------------------------
automation:
  - id: contact_sensor_auto_monitor
    alias: Contact Sensor - Auto Monitor All Sensors
    description: |
      Automatically monitors all contact sensors and sends notifications
      when left open too long.

    mode: parallel  # Each sensor runs independently
    max: 50  # Max concurrent sensor alerts
    max_exceeded: silent

    variables:
      # Notification service (customize this!)
      notify_service: "notify.mobile_app_your_phone"  # CHANGE THIS

      # Get global settings from helpers
      delay_minutes: "{{ states('input_number.contact_sensor_delay_minutes') | int(10) }}"
      is_critical: "{{ is_state('input_boolean.contact_sensor_critical_alert', 'on') }}"

    trigger:
      # Trigger on ANY binary_sensor state change
      - platform: state
        entity_id: binary_sensor
        to:
          - "on"
          - "off"

    condition:
      # Only proceed if this is a contact sensor
      - condition: template
        value_template: >
          {% set device_class = state_attr(trigger.entity_id, 'device_class') %}
          {{ device_class in ['door', 'window', 'opening', 'garage_door'] }}

    action:
      - variables:
          # Store sensor information
          sensor_entity_id: "{{ trigger.entity_id }}"
          sensor_name: "{{ state_attr(trigger.entity_id, 'friendly_name') }}"
          sensor_area: "{{ area_name(trigger.entity_id) | default('Unknown', true) }}"

          # Notification data for iOS critical alerts
          notification_data: >
            {% if is_critical %}
              {"push": {"sound": {"name": "default", "critical": 1, "volume": 1.0}}}
            {% else %}
              {}
            {% endif %}

      - choose:
          # === SENSOR OPENED ===
          - conditions:
              - condition: template
                value_template: "{{ trigger.to_state.state == 'on' }}"
            sequence:
              # Wait for the configured delay
              - delay:
                  minutes: "{{ delay_minutes }}"

              # Check if still open after delay
              - condition: template
                value_template: "{{ is_state(sensor_entity_id, 'on') }}"

              # Calculate time open
              - variables:
                  time_open: >
                    {% set opened_at = states[sensor_entity_id].last_changed %}
                    {% set duration = now() - opened_at %}
                    {% set hours = duration.total_seconds() // 3600 %}
                    {% set minutes_calc = (duration.total_seconds() % 3600) // 60 %}
                    {% if hours > 0 %}
                      {{ hours | int }} hour{{ 's' if hours > 1 else '' }}
                      and {{ minutes_calc | int }} minute{{ 's' if minutes_calc != 1 else '' }}
                    {% else %}
                      {{ minutes_calc | int }} minute{{ 's' if minutes_calc != 1 else '' }}
                    {% endif %}

              # Send notification
              - service: "{{ notify_service }}"
                data:
                  title: "{{ sensor_name }} Left Open"
                  message: >
                    {{ sensor_name }}{% if sensor_area != 'Unknown' %} in {{ sensor_area }}{% endif %}
                    has been open for {{ time_open }}
                  data: >
                    {{ dict(notification_data | from_json, **{'tag': 'contact_sensor_' + (sensor_entity_id | replace('.', '_'))}) }}

          # === SENSOR CLOSED ===
          - conditions:
              - condition: template
                value_template: "{{ trigger.to_state.state == 'off' }}"
            sequence:
              # Clear the notification
              - service: "{{ notify_service }}"
                data:
                  message: "clear_notification"
                  data:
                    tag: "contact_sensor_{{ sensor_entity_id | replace('.', '_') }}"


# ============================================================================
# CUSTOMIZATION OPTIONS
# ============================================================================
#
# 1. Change notification service:
#    Find the line: notify_service: "notify.mobile_app_your_phone"
#    Replace with your notification service (e.g., notify.mobile_app_iphone)
#
# 2. Adjust global delay:
#    Go to Settings → Helpers → "Contact Sensor Delay (Minutes)"
#    Change the value (default: 10 minutes)
#
# 3. Enable critical notifications:
#    Go to Settings → Helpers → "Contact Sensor Critical Alert"
#    Toggle ON to enable critical notifications (iOS bypasses Do Not Disturb)
#
# 4. Filter specific sensors only:
#    Replace the trigger entity_id line with a list:
#    entity_id:
#      - binary_sensor.front_door
#      - binary_sensor.back_door
#
# 5. Customize notification messages:
#    Edit the notification title and message templates
#
# 6. Add custom actions:
#    Add additional service calls in the sequences (flash lights, TTS, etc.)
#
# ============================================================================
#
# NOTE: For hierarchical configuration (different delays per area/floor/entity),
# use the blueprint approach instead. This package provides a simple global
# configuration for all sensors.
#
# ============================================================================
